# app 1
spring:
  cloud:
    stream:
      bindings:
        output_channel:       #channelName
          destination: mydest #destination，或者可以认为是发布－订阅模型里面的topic
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 10.5.16.14   #rabbitMQ服务器地址
                port: 5672          #rabbitMQ服务器端口
#                username: guest
#                password: guest
#                virtual-host: /hostName
  application:
      # This ends up as the service name in zipkin
      name: stream-sleuth
  zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
     baseUrl: http://10.5.16.14:9411/
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8090

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: true
#
## app 2
#server:
#  port: 8099
#spring:
#  cloud:
#    stream:
#      bindings:
#        input_channel:
#          destination: mydest #position2。destination，或者可以认为是发布－订阅模型里面的topic，这里应该与输出app中发布的topic一致，表示订阅该主题
#          binder: rabbit1
#      binders:
#        rabbit1:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: 10.5.16.14   #rabbitMQ服务器地址
#                port: 5672          #rabbitMQ服务器端口
##                username: guest
##                password: guest
##                virtual-host: /hostName