eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/

spring:
  application:
    name: test-client
  zipkin:
    base-url: http://10.5.16.14:9411/
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 10003

## ribbon直接映射注册到eureka的服务
ribbon:
  eureka:
    enabled: true

zuul:
  ignoredServices: '*'
  routes:
    test-service: /test/**


netflix:
  atlas:
    uri: http://10.5.16.14:7101/api/v1/publish/

logging:
  level:
    info:
     developerblog: debug

info:
  component: eureka-client