/**
 * This class is generated by jOOQ
 */
package com.wch.jooq.entity.tables.records;


import com.wch.jooq.entity.tables.TEntry;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 分录（变化明细）
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TEntryRecord extends UpdatableRecordImpl<TEntryRecord> implements Record13<Long, BigDecimal, String, String, String, String, String, BigDecimal, BigDecimal, String, Timestamp, String, String> {

	private static final long serialVersionUID = -863703257;

	/**
	 * Setter for <code>optimus.t_entry.entry_id</code>.
	 */
	public void setEntryId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>optimus.t_entry.entry_id</code>.
	 */
	public Long getEntryId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>optimus.t_entry.amount</code>. 金额
	 */
	public void setAmount(BigDecimal value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>optimus.t_entry.amount</code>. 金额
	 */
	public BigDecimal getAmount() {
		return (BigDecimal) getValue(1);
	}

	/**
	 * Setter for <code>optimus.t_entry.order_id</code>. 交易id
	 */
	public void setOrderId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>optimus.t_entry.order_id</code>. 交易id
	 */
	public String getOrderId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>optimus.t_entry.order_type</code>. 交易类型
	 */
	public void setOrderType(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>optimus.t_entry.order_type</code>. 交易类型
	 */
	public String getOrderType() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>optimus.t_entry.dc</code>. +  -
	 */
	public void setDc(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>optimus.t_entry.dc</code>. +  -
	 */
	public String getDc() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>optimus.t_entry.member_id</code>. 会员id
	 */
	public void setMemberId(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>optimus.t_entry.member_id</code>. 会员id
	 */
	public String getMemberId() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>optimus.t_entry.account_id</code>. 账户id
	 */
	public void setAccountId(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>optimus.t_entry.account_id</code>. 账户id
	 */
	public String getAccountId() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>optimus.t_entry.after_balance</code>.
	 */
	public void setAfterBalance(BigDecimal value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>optimus.t_entry.after_balance</code>.
	 */
	public BigDecimal getAfterBalance() {
		return (BigDecimal) getValue(7);
	}

	/**
	 * Setter for <code>optimus.t_entry.before_balance</code>.
	 */
	public void setBeforeBalance(BigDecimal value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>optimus.t_entry.before_balance</code>.
	 */
	public BigDecimal getBeforeBalance() {
		return (BigDecimal) getValue(8);
	}

	/**
	 * Setter for <code>optimus.t_entry.digest</code>. 摘要
	 */
	public void setDigest(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>optimus.t_entry.digest</code>. 摘要
	 */
	public String getDigest() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>optimus.t_entry.create_time</code>.
	 */
	public void setCreateTime(Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>optimus.t_entry.create_time</code>.
	 */
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>optimus.t_entry.ext1</code>.
	 */
	public void setExt1(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>optimus.t_entry.ext1</code>.
	 */
	public String getExt1() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>optimus.t_entry.ext2</code>.
	 */
	public void setExt2(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>optimus.t_entry.ext2</code>.
	 */
	public String getExt2() {
		return (String) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Long, BigDecimal, String, String, String, String, String, BigDecimal, BigDecimal, String, Timestamp, String, String> fieldsRow() {
		return (Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Long, BigDecimal, String, String, String, String, String, BigDecimal, BigDecimal, String, Timestamp, String, String> valuesRow() {
		return (Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return TEntry.T_ENTRY.ENTRY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field2() {
		return TEntry.T_ENTRY.AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TEntry.T_ENTRY.ORDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TEntry.T_ENTRY.ORDER_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TEntry.T_ENTRY.DC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TEntry.T_ENTRY.MEMBER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return TEntry.T_ENTRY.ACCOUNT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field8() {
		return TEntry.T_ENTRY.AFTER_BALANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field9() {
		return TEntry.T_ENTRY.BEFORE_BALANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return TEntry.T_ENTRY.DIGEST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return TEntry.T_ENTRY.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return TEntry.T_ENTRY.EXT1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return TEntry.T_ENTRY.EXT2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getEntryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value2() {
		return getAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getOrderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getOrderType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getDc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getMemberId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value8() {
		return getAfterBalance();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value9() {
		return getBeforeBalance();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getDigest();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getExt1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getExt2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord value1(Long value) {
		setEntryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord value2(BigDecimal value) {
		setAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord value3(String value) {
		setOrderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord value4(String value) {
		setOrderType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord value5(String value) {
		setDc(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord value6(String value) {
		setMemberId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord value7(String value) {
		setAccountId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord value8(BigDecimal value) {
		setAfterBalance(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord value9(BigDecimal value) {
		setBeforeBalance(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord value10(String value) {
		setDigest(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord value11(Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord value12(String value) {
		setExt1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord value13(String value) {
		setExt2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TEntryRecord values(Long value1, BigDecimal value2, String value3, String value4, String value5, String value6, String value7, BigDecimal value8, BigDecimal value9, String value10, Timestamp value11, String value12, String value13) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TEntryRecord
	 */
	public TEntryRecord() {
		super(TEntry.T_ENTRY);
	}

	/**
	 * Create a detached, initialised TEntryRecord
	 */
	public TEntryRecord(Long entryId, BigDecimal amount, String orderId, String orderType, String dc, String memberId, String accountId, BigDecimal afterBalance, BigDecimal beforeBalance, String digest, Timestamp createTime, String ext1, String ext2) {
		super(TEntry.T_ENTRY);

		setValue(0, entryId);
		setValue(1, amount);
		setValue(2, orderId);
		setValue(3, orderType);
		setValue(4, dc);
		setValue(5, memberId);
		setValue(6, accountId);
		setValue(7, afterBalance);
		setValue(8, beforeBalance);
		setValue(9, digest);
		setValue(10, createTime);
		setValue(11, ext1);
		setValue(12, ext2);
	}
}
