/**
 * This class is generated by jOOQ
 */
package com.wch.jooq.entity.tables.records;


import com.wch.jooq.entity.tables.TMember;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMemberRecord extends UpdatableRecordImpl<TMemberRecord> implements Record14<String, String, String, String, String, String, String, Timestamp, Timestamp, String, Timestamp, String, String, String> {

	private static final long serialVersionUID = 976607009;

	/**
	 * Setter for <code>optimus.t_member.member_id</code>. 用户id  
	 */
	public void setMemberId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>optimus.t_member.member_id</code>. 用户id  
	 */
	public String getMemberId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>optimus.t_member.chan_id</code>. 渠道id
	 */
	public void setChanId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>optimus.t_member.chan_id</code>. 渠道id
	 */
	public String getChanId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>optimus.t_member.chan_user_id</code>. 渠道用户id
	 */
	public void setChanUserId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>optimus.t_member.chan_user_id</code>. 渠道用户id
	 */
	public String getChanUserId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>optimus.t_member.chan_user_name</code>. 渠道用户名
	 */
	public void setChanUserName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>optimus.t_member.chan_user_name</code>. 渠道用户名
	 */
	public String getChanUserName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>optimus.t_member.mobile</code>. 手机号
	 */
	public void setMobile(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>optimus.t_member.mobile</code>. 手机号
	 */
	public String getMobile() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>optimus.t_member.account_id</code>. 账户id
	 */
	public void setAccountId(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>optimus.t_member.account_id</code>. 账户id
	 */
	public String getAccountId() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>optimus.t_member.pay_passwd</code>. 支付密码
	 */
	public void setPayPasswd(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>optimus.t_member.pay_passwd</code>. 支付密码
	 */
	public String getPayPasswd() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>optimus.t_member.create_time</code>. 创建时间
	 */
	public void setCreateTime(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>optimus.t_member.create_time</code>. 创建时间
	 */
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>optimus.t_member.update_time</code>. 最后更新时间
	 */
	public void setUpdateTime(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>optimus.t_member.update_time</code>. 最后更新时间
	 */
	public Timestamp getUpdateTime() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>optimus.t_member.status</code>. 状态  Normal：正常     Lock：密码错误锁定     Freeze：风控冻结 
	 */
	public void setStatus(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>optimus.t_member.status</code>. 状态  Normal：正常     Lock：密码错误锁定     Freeze：风控冻结 
	 */
	public String getStatus() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>optimus.t_member.lock_time</code>. 锁定时间
	 */
	public void setLockTime(Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>optimus.t_member.lock_time</code>. 锁定时间
	 */
	public Timestamp getLockTime() {
		return (Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>optimus.t_member.type</code>. 类型 INVEST:投资账户,ADMIN:管理账户
	 */
	public void setType(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>optimus.t_member.type</code>. 类型 INVEST:投资账户,ADMIN:管理账户
	 */
	public String getType() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>optimus.t_member.chan_user_realname</code>. 渠道用户真实姓名
	 */
	public void setChanUserRealname(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>optimus.t_member.chan_user_realname</code>. 渠道用户真实姓名
	 */
	public String getChanUserRealname() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>optimus.t_member.chan_user_id_number</code>. 渠道用户身份证编号
	 */
	public void setChanUserIdNumber(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>optimus.t_member.chan_user_id_number</code>. 渠道用户身份证编号
	 */
	public String getChanUserIdNumber() {
		return (String) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<String, String, String, String, String, String, String, Timestamp, Timestamp, String, Timestamp, String, String, String> fieldsRow() {
		return (Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<String, String, String, String, String, String, String, Timestamp, Timestamp, String, Timestamp, String, String, String> valuesRow() {
		return (Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TMember.T_MEMBER.MEMBER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TMember.T_MEMBER.CHAN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TMember.T_MEMBER.CHAN_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TMember.T_MEMBER.CHAN_USER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TMember.T_MEMBER.MOBILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TMember.T_MEMBER.ACCOUNT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return TMember.T_MEMBER.PAY_PASSWD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return TMember.T_MEMBER.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return TMember.T_MEMBER.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return TMember.T_MEMBER.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return TMember.T_MEMBER.LOCK_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return TMember.T_MEMBER.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return TMember.T_MEMBER.CHAN_USER_REALNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field14() {
		return TMember.T_MEMBER.CHAN_USER_ID_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getMemberId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getChanId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getChanUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getChanUserName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getMobile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getPayPasswd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getLockTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getChanUserRealname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value14() {
		return getChanUserIdNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value1(String value) {
		setMemberId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value2(String value) {
		setChanId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value3(String value) {
		setChanUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value4(String value) {
		setChanUserName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value5(String value) {
		setMobile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value6(String value) {
		setAccountId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value7(String value) {
		setPayPasswd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value8(Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value9(Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value10(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value11(Timestamp value) {
		setLockTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value12(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value13(String value) {
		setChanUserRealname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord value14(String value) {
		setChanUserIdNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TMemberRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, Timestamp value8, Timestamp value9, String value10, Timestamp value11, String value12, String value13, String value14) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TMemberRecord
	 */
	public TMemberRecord() {
		super(TMember.T_MEMBER);
	}

	/**
	 * Create a detached, initialised TMemberRecord
	 */
	public TMemberRecord(String memberId, String chanId, String chanUserId, String chanUserName, String mobile, String accountId, String payPasswd, Timestamp createTime, Timestamp updateTime, String status, Timestamp lockTime, String type, String chanUserRealname, String chanUserIdNumber) {
		super(TMember.T_MEMBER);

		setValue(0, memberId);
		setValue(1, chanId);
		setValue(2, chanUserId);
		setValue(3, chanUserName);
		setValue(4, mobile);
		setValue(5, accountId);
		setValue(6, payPasswd);
		setValue(7, createTime);
		setValue(8, updateTime);
		setValue(9, status);
		setValue(10, lockTime);
		setValue(11, type);
		setValue(12, chanUserRealname);
		setValue(13, chanUserIdNumber);
	}
}
