/**
 * This class is generated by jOOQ
 */
package com.wch.jooq.entity.tables.records;


import com.wch.jooq.entity.tables.TDict;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDictRecord extends UpdatableRecordImpl<TDictRecord> implements Record4<String, String, String, String> {

	private static final long serialVersionUID = 1824662925;

	/**
	 * Setter for <code>optimus.t_dict.id</code>. 键
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>optimus.t_dict.id</code>. 键
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>optimus.t_dict.value</code>. 值
	 */
	public void setValue(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>optimus.t_dict.value</code>. 值
	 */
	public String getValue() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>optimus.t_dict.type</code>. 类型;CHAN:渠道,AUTH:授权信息
	 */
	public void setType(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>optimus.t_dict.type</code>. 类型;CHAN:渠道,AUTH:授权信息
	 */
	public String getType() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>optimus.t_dict.description</code>. 描述信息
	 */
	public void setDescription(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>optimus.t_dict.description</code>. 描述信息
	 */
	public String getDescription() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, String, String, String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, String, String, String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TDict.T_DICT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TDict.T_DICT.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TDict.T_DICT.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TDict.T_DICT.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TDictRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TDictRecord value2(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TDictRecord value3(String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TDictRecord value4(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TDictRecord values(String value1, String value2, String value3, String value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TDictRecord
	 */
	public TDictRecord() {
		super(TDict.T_DICT);
	}

	/**
	 * Create a detached, initialised TDictRecord
	 */
	public TDictRecord(String id, String value, String type, String description) {
		super(TDict.T_DICT);

		setValue(0, id);
		setValue(1, value);
		setValue(2, type);
		setValue(3, description);
	}
}
