/**
 * This class is generated by jOOQ
 */
package com.wch.jooq.entity.tables.records;


import com.wch.jooq.entity.tables.TOrder;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrderRecord extends UpdatableRecordImpl<TOrderRecord> implements Record14<String, String, String, String, String, String, BigDecimal, String, String, String, Timestamp, Timestamp, String, String> {

	private static final long serialVersionUID = -578789756;

	/**
	 * Setter for <code>optimus.t_order.order_id</code>.
	 */
	public void setOrderId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>optimus.t_order.order_id</code>.
	 */
	public String getOrderId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>optimus.t_order.chan_id</code>. 渠道id
	 */
	public void setChanId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>optimus.t_order.chan_id</code>. 渠道id
	 */
	public String getChanId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>optimus.t_order.chan_user_id</code>. 渠道用户id
	 */
	public void setChanUserId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>optimus.t_order.chan_user_id</code>. 渠道用户id
	 */
	public String getChanUserId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>optimus.t_order.member_id</code>. 会员id
	 */
	public void setMemberId(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>optimus.t_order.member_id</code>. 会员id
	 */
	public String getMemberId() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>optimus.t_order.order_type</code>. 类型 deposit withdraw apply redeem
	 */
	public void setOrderType(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>optimus.t_order.order_type</code>. 类型 deposit withdraw apply redeem
	 */
	public String getOrderType() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>optimus.t_order.product_id</code>. 产品id
	 */
	public void setProductId(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>optimus.t_order.product_id</code>. 产品id
	 */
	public String getProductId() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>optimus.t_order.amount</code>. 充值金额
	 */
	public void setAmount(BigDecimal value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>optimus.t_order.amount</code>. 充值金额
	 */
	public BigDecimal getAmount() {
		return (BigDecimal) getValue(6);
	}

	/**
	 * Setter for <code>optimus.t_order.outer_order_id</code>. 外部id
	 */
	public void setOuterOrderId(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>optimus.t_order.outer_order_id</code>. 外部id
	 */
	public String getOuterOrderId() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>optimus.t_order.order_status</code>. 状态: I 初始   P 处理中 S 成功  F失败 
	 */
	public void setOrderStatus(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>optimus.t_order.order_status</code>. 状态: I 初始   P 处理中 S 成功  F失败 
	 */
	public String getOrderStatus() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>optimus.t_order.memo</code>. 备注
	 */
	public void setMemo(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>optimus.t_order.memo</code>. 备注
	 */
	public String getMemo() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>optimus.t_order.order_time</code>.
	 */
	public void setOrderTime(Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>optimus.t_order.order_time</code>.
	 */
	public Timestamp getOrderTime() {
		return (Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>optimus.t_order.update_time</code>.
	 */
	public void setUpdateTime(Timestamp value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>optimus.t_order.update_time</code>.
	 */
	public Timestamp getUpdateTime() {
		return (Timestamp) getValue(11);
	}

	/**
	 * Setter for <code>optimus.t_order.ext1</code>. 扩展1 可用于操作员
	 */
	public void setExt1(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>optimus.t_order.ext1</code>. 扩展1 可用于操作员
	 */
	public String getExt1() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>optimus.t_order.ext2</code>. 扩展2 可用于审核员
	 */
	public void setExt2(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>optimus.t_order.ext2</code>. 扩展2 可用于审核员
	 */
	public String getExt2() {
		return (String) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<String, String, String, String, String, String, BigDecimal, String, String, String, Timestamp, Timestamp, String, String> fieldsRow() {
		return (Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<String, String, String, String, String, String, BigDecimal, String, String, String, Timestamp, Timestamp, String, String> valuesRow() {
		return (Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TOrder.T_ORDER.ORDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TOrder.T_ORDER.CHAN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TOrder.T_ORDER.CHAN_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TOrder.T_ORDER.MEMBER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TOrder.T_ORDER.ORDER_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TOrder.T_ORDER.PRODUCT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field7() {
		return TOrder.T_ORDER.AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return TOrder.T_ORDER.OUTER_ORDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return TOrder.T_ORDER.ORDER_STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return TOrder.T_ORDER.MEMO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return TOrder.T_ORDER.ORDER_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field12() {
		return TOrder.T_ORDER.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return TOrder.T_ORDER.EXT1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field14() {
		return TOrder.T_ORDER.EXT2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getOrderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getChanId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getChanUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getMemberId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getOrderType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getProductId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value7() {
		return getAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getOuterOrderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getOrderStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getMemo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getOrderTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value12() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getExt1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value14() {
		return getExt2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value1(String value) {
		setOrderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value2(String value) {
		setChanId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value3(String value) {
		setChanUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value4(String value) {
		setMemberId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value5(String value) {
		setOrderType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value6(String value) {
		setProductId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value7(BigDecimal value) {
		setAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value8(String value) {
		setOuterOrderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value9(String value) {
		setOrderStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value10(String value) {
		setMemo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value11(Timestamp value) {
		setOrderTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value12(Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value13(String value) {
		setExt1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord value14(String value) {
		setExt2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TOrderRecord values(String value1, String value2, String value3, String value4, String value5, String value6, BigDecimal value7, String value8, String value9, String value10, Timestamp value11, Timestamp value12, String value13, String value14) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TOrderRecord
	 */
	public TOrderRecord() {
		super(TOrder.T_ORDER);
	}

	/**
	 * Create a detached, initialised TOrderRecord
	 */
	public TOrderRecord(String orderId, String chanId, String chanUserId, String memberId, String orderType, String productId, BigDecimal amount, String outerOrderId, String orderStatus, String memo, Timestamp orderTime, Timestamp updateTime, String ext1, String ext2) {
		super(TOrder.T_ORDER);

		setValue(0, orderId);
		setValue(1, chanId);
		setValue(2, chanUserId);
		setValue(3, memberId);
		setValue(4, orderType);
		setValue(5, productId);
		setValue(6, amount);
		setValue(7, outerOrderId);
		setValue(8, orderStatus);
		setValue(9, memo);
		setValue(10, orderTime);
		setValue(11, updateTime);
		setValue(12, ext1);
		setValue(13, ext2);
	}
}
