## 端口
server:
  port: 10001


## 该应用名字
spring:
  application:
    name: test-server
  cloud:
    task:
      closecontext:
        enabled: false
  zipkin:
    base-url: http://10.5.16.14:9411/
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0


## eureka server相关配置
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: 10.5.16.4
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #http://peer2:10002/eureka
logging:
  level:
    org:
      springframework:
        cloud:
          task: DEBUG
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
