## 端口
server:
  port: 10002


## 该应用名字
spring:
  application:
    name: test-server

## eureka server相关配置
eureka:
  instance:
    hostname: peer2
    leaseRenewalIntervalInSeconds: 3
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:10001/eureka
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
