## 端口
server:
  port: 10001


## 该应用名字
spring:
  application:
    name: test-server
  cloud:
    task:
      closecontext:
        enabled: false

## eureka server相关配置
eureka:
  instance:
    hostname: peer1
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:10002/eureka
logging:
  level:
    org:
      springframework:
        cloud:
          task: DEBUG
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/