/**
 * This class is generated by jOOQ
 */
package org.wch.jooq.entity.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.wch.jooq.entity.tables.TAccount;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountRecord extends UpdatableRecordImpl<TAccountRecord> implements Record10<String, String, String, BigDecimal, BigDecimal, BigDecimal, String, BigDecimal, Timestamp, Timestamp> {

	private static final long serialVersionUID = -1074291720;

	/**
	 * Setter for <code>optimus.t_account.account_id</code>. 账号id
	 */
	public void setAccountId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>optimus.t_account.account_id</code>. 账号id
	 */
	public String getAccountId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>optimus.t_account.account_name</code>. 名称
	 */
	public void setAccountName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>optimus.t_account.account_name</code>. 名称
	 */
	public String getAccountName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>optimus.t_account.account_title_no</code>. 账户科目号
	 */
	public void setAccountTitleNo(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>optimus.t_account.account_title_no</code>. 账户科目号
	 */
	public String getAccountTitleNo() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>optimus.t_account.balance</code>. 余额
	 */
	public void setBalance(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>optimus.t_account.balance</code>. 余额
	 */
	public BigDecimal getBalance() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>optimus.t_account.debitBalance</code>. 借方余额
	 */
	public void setDebitbalance(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>optimus.t_account.debitBalance</code>. 借方余额
	 */
	public BigDecimal getDebitbalance() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>optimus.t_account.creditBalance</code>. 贷方余额
	 */
	public void setCreditbalance(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>optimus.t_account.creditBalance</code>. 贷方余额
	 */
	public BigDecimal getCreditbalance() {
		return (BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>optimus.t_account.balance_direction</code>. D：借方  C：贷方
	 */
	public void setBalanceDirection(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>optimus.t_account.balance_direction</code>. D：借方  C：贷方
	 */
	public String getBalanceDirection() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>optimus.t_account.frozen_balance</code>. 冻结余额
	 */
	public void setFrozenBalance(BigDecimal value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>optimus.t_account.frozen_balance</code>. 冻结余额
	 */
	public BigDecimal getFrozenBalance() {
		return (BigDecimal) getValue(7);
	}

	/**
	 * Setter for <code>optimus.t_account.create_time</code>.
	 */
	public void setCreateTime(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>optimus.t_account.create_time</code>.
	 */
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>optimus.t_account.update_time</code>.
	 */
	public void setUpdateTime(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>optimus.t_account.update_time</code>.
	 */
	public Timestamp getUpdateTime() {
		return (Timestamp) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<String, String, String, BigDecimal, BigDecimal, BigDecimal, String, BigDecimal, Timestamp, Timestamp> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<String, String, String, BigDecimal, BigDecimal, BigDecimal, String, BigDecimal, Timestamp, Timestamp> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TAccount.T_ACCOUNT.ACCOUNT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TAccount.T_ACCOUNT.ACCOUNT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TAccount.T_ACCOUNT.ACCOUNT_TITLE_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field4() {
		return TAccount.T_ACCOUNT.BALANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field5() {
		return TAccount.T_ACCOUNT.DEBITBALANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field6() {
		return TAccount.T_ACCOUNT.CREDITBALANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return TAccount.T_ACCOUNT.BALANCE_DIRECTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field8() {
		return TAccount.T_ACCOUNT.FROZEN_BALANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return TAccount.T_ACCOUNT.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return TAccount.T_ACCOUNT.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAccountName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAccountTitleNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value4() {
		return getBalance();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value5() {
		return getDebitbalance();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value6() {
		return getCreditbalance();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getBalanceDirection();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value8() {
		return getFrozenBalance();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAccountRecord value1(String value) {
		setAccountId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAccountRecord value2(String value) {
		setAccountName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAccountRecord value3(String value) {
		setAccountTitleNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAccountRecord value4(BigDecimal value) {
		setBalance(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAccountRecord value5(BigDecimal value) {
		setDebitbalance(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAccountRecord value6(BigDecimal value) {
		setCreditbalance(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAccountRecord value7(String value) {
		setBalanceDirection(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAccountRecord value8(BigDecimal value) {
		setFrozenBalance(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAccountRecord value9(Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAccountRecord value10(Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TAccountRecord values(String value1, String value2, String value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, String value7, BigDecimal value8, Timestamp value9, Timestamp value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TAccountRecord
	 */
	public TAccountRecord() {
		super(TAccount.T_ACCOUNT);
	}

	/**
	 * Create a detached, initialised TAccountRecord
	 */
	public TAccountRecord(String accountId, String accountName, String accountTitleNo, BigDecimal balance, BigDecimal debitbalance, BigDecimal creditbalance, String balanceDirection, BigDecimal frozenBalance, Timestamp createTime, Timestamp updateTime) {
		super(TAccount.T_ACCOUNT);

		setValue(0, accountId);
		setValue(1, accountName);
		setValue(2, accountTitleNo);
		setValue(3, balance);
		setValue(4, debitbalance);
		setValue(5, creditbalance);
		setValue(6, balanceDirection);
		setValue(7, frozenBalance);
		setValue(8, createTime);
		setValue(9, updateTime);
	}
}
