/**
 * This class is generated by jOOQ
 */
package org.wch.jooq.entity.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.wch.jooq.entity.tables.TPayment;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPaymentRecord extends UpdatableRecordImpl<TPaymentRecord> implements Record11<String, String, String, String, BigDecimal, String, String, String, Timestamp, String, String> {

	private static final long serialVersionUID = -1175773764;

	/**
	 * Setter for <code>optimus.t_payment.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>optimus.t_payment.id</code>.
	 */
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>optimus.t_payment.order_id</code>. 关联订单编号，确认是否已经进行了出入款
	 */
	public void setOrderId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>optimus.t_payment.order_id</code>. 关联订单编号，确认是否已经进行了出入款
	 */
	public String getOrderId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>optimus.t_payment.subject_no</code>. 产品编号
	 */
	public void setSubjectNo(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>optimus.t_payment.subject_no</code>. 产品编号
	 */
	public String getSubjectNo() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>optimus.t_payment.subject_name</code>. 产品名称
	 */
	public void setSubjectName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>optimus.t_payment.subject_name</code>. 产品名称
	 */
	public String getSubjectName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>optimus.t_payment.amount</code>. 金额
	 */
	public void setAmount(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>optimus.t_payment.amount</code>. 金额
	 */
	public BigDecimal getAmount() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>optimus.t_payment.payment_type</code>. 出入款类型,PAYMENT_OUT:出款,PAYMENT_IN:入款
	 */
	public void setPaymentType(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>optimus.t_payment.payment_type</code>. 出入款类型,PAYMENT_OUT:出款,PAYMENT_IN:入款
	 */
	public String getPaymentType() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>optimus.t_payment.action_type</code>. 操作类型,ACTION_LOAN:放款,ACTION_REPAYMENT:还款,ACTION_APPLY:申购,ACTION_REDEEM:赎回
	 */
	public void setActionType(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>optimus.t_payment.action_type</code>. 操作类型,ACTION_LOAN:放款,ACTION_REPAYMENT:还款,ACTION_APPLY:申购,ACTION_REDEEM:赎回
	 */
	public String getActionType() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>optimus.t_payment.subject_type</code>. 产品类型,SUBJECT:定期产品,FUND:基金
	 */
	public void setSubjectType(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>optimus.t_payment.subject_type</code>. 产品类型,SUBJECT:定期产品,FUND:基金
	 */
	public String getSubjectType() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>optimus.t_payment.create_time</code>. 创建时间
	 */
	public void setCreateTime(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>optimus.t_payment.create_time</code>. 创建时间
	 */
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>optimus.t_payment.plat</code>. 所属平台编码
	 */
	public void setPlat(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>optimus.t_payment.plat</code>. 所属平台编码
	 */
	public String getPlat() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>optimus.t_payment.to_plat</code>. 渠道平台编码
	 */
	public void setToPlat(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>optimus.t_payment.to_plat</code>. 渠道平台编码
	 */
	public String getToPlat() {
		return (String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<String, String, String, String, BigDecimal, String, String, String, Timestamp, String, String> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<String, String, String, String, BigDecimal, String, String, String, Timestamp, String, String> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TPayment.T_PAYMENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TPayment.T_PAYMENT.ORDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TPayment.T_PAYMENT.SUBJECT_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TPayment.T_PAYMENT.SUBJECT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field5() {
		return TPayment.T_PAYMENT.AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return TPayment.T_PAYMENT.PAYMENT_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return TPayment.T_PAYMENT.ACTION_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return TPayment.T_PAYMENT.SUBJECT_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return TPayment.T_PAYMENT.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return TPayment.T_PAYMENT.PLAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return TPayment.T_PAYMENT.TO_PLAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getOrderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSubjectNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getSubjectName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value5() {
		return getAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getPaymentType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getActionType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getSubjectType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getPlat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getToPlat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TPaymentRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TPaymentRecord value2(String value) {
		setOrderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TPaymentRecord value3(String value) {
		setSubjectNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TPaymentRecord value4(String value) {
		setSubjectName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TPaymentRecord value5(BigDecimal value) {
		setAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TPaymentRecord value6(String value) {
		setPaymentType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TPaymentRecord value7(String value) {
		setActionType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TPaymentRecord value8(String value) {
		setSubjectType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TPaymentRecord value9(Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TPaymentRecord value10(String value) {
		setPlat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TPaymentRecord value11(String value) {
		setToPlat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TPaymentRecord values(String value1, String value2, String value3, String value4, BigDecimal value5, String value6, String value7, String value8, Timestamp value9, String value10, String value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TPaymentRecord
	 */
	public TPaymentRecord() {
		super(TPayment.T_PAYMENT);
	}

	/**
	 * Create a detached, initialised TPaymentRecord
	 */
	public TPaymentRecord(String id, String orderId, String subjectNo, String subjectName, BigDecimal amount, String paymentType, String actionType, String subjectType, Timestamp createTime, String plat, String toPlat) {
		super(TPayment.T_PAYMENT);

		setValue(0, id);
		setValue(1, orderId);
		setValue(2, subjectNo);
		setValue(3, subjectName);
		setValue(4, amount);
		setValue(5, paymentType);
		setValue(6, actionType);
		setValue(7, subjectType);
		setValue(8, createTime);
		setValue(9, plat);
		setValue(10, toPlat);
	}
}
