/**
 * This class is generated by jOOQ
 */
package org.wch.jooq.entity;


import javax.annotation.Generated;

import org.wch.jooq.entity.tables.TAccount;
import org.wch.jooq.entity.tables.TChanView;
import org.wch.jooq.entity.tables.TDict;
import org.wch.jooq.entity.tables.TEntry;
import org.wch.jooq.entity.tables.TMember;
import org.wch.jooq.entity.tables.TOrder;
import org.wch.jooq.entity.tables.TPayment;
import org.wch.jooq.entity.tables.TSequence;


/**
 * Convenience access to all tables in optimus
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table optimus.t_account
	 */
	public static final TAccount T_ACCOUNT = org.wch.jooq.entity.tables.TAccount.T_ACCOUNT;

	/**
	 * The table optimus.t_chan_view
	 */
	public static final TChanView T_CHAN_VIEW = org.wch.jooq.entity.tables.TChanView.T_CHAN_VIEW;

	/**
	 * The table optimus.t_dict
	 */
	public static final TDict T_DICT = org.wch.jooq.entity.tables.TDict.T_DICT;

	/**
	 * 分录（变化明细）
	 */
	public static final TEntry T_ENTRY = org.wch.jooq.entity.tables.TEntry.T_ENTRY;

	/**
	 * The table optimus.t_member
	 */
	public static final TMember T_MEMBER = org.wch.jooq.entity.tables.TMember.T_MEMBER;

	/**
	 * The table optimus.t_order
	 */
	public static final TOrder T_ORDER = org.wch.jooq.entity.tables.TOrder.T_ORDER;

	/**
	 * The table optimus.t_payment
	 */
	public static final TPayment T_PAYMENT = org.wch.jooq.entity.tables.TPayment.T_PAYMENT;

	/**
	 * The table optimus.t_sequence
	 */
	public static final TSequence T_SEQUENCE = org.wch.jooq.entity.tables.TSequence.T_SEQUENCE;
}
