eureka:
  instance:
#    instance-id: host-${eureka.instance.hostname}:${eureka.instance.non-secure-port}
    prefer-ip-address: true

    # 下面的变量可以使用环境变量进行设置eureka.instance.non-secure-port
#    non-secure-port: 1122
#    ip-address: ${envirment.ip}
#    hostname:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
#      http://localhost:10001/eureka/,http://localhost:10002/eureka/

spring:
  application:
    name: test-service
  zipkin:
#    base-url: http://10.5.16.14:9411/
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: 10.5.16.14
    port: 5672
server:
  port: 10005
logging:
  level:
    info:
     developerblog: debug
#    org:
#      springframework: debug